version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql-initdb:/docker-entrypoint-initdb.d  # Mount the initialization script
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app-network
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "22:22"  # Forward SSH on port 22
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge

