version: '3.8'

services:
  php:
    image: php:8.0-fpm
    container_name: php_test
    volumes:
      - ./src:/var/www/html  # Your PHP codebase for test.nl
    networks:
      - shared-network

  ssh:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: ssh_test
    restart: always
    environment:
      - ROOT_PASSWORD=test_ssh_password  # Set SSH password for root
    networks:
      - shared-network
    expose:
      - "22"  # Expose port 22 internally

networks:
  shared-network:
    external: true
